apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJibVZ6WkhNNloyaHdYMDVuV1VwQ2FscEdiMkZoUTJOdE9IVlpkbXRRVG1zMVMyTjVRVWRDTURGWE4yY3hjUT09In19fQ==
type: kubernetes.io/dockerconfigjson
